#!/bin/sh

# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vi="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias bat="cat /sys/class/power_supply/BAT?/capacity" \

# Colorize commands when possible.
#ls="ls -hN --color=auto --group-directories-first" \
alias \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# "exa" is better alternative to "ls"
alias ls='exa -l --color=always --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git"

alias vimconf='nvim ~/.config/nvim/init.vim'
alias vimi3='nvim ~/.config/i3/config'
alias config='/usr/bin/git --git-dir=/home/dzmitry/.cfg/ --work-tree=/home/dzmitry'
alias vimbar='nvim ~/.config/polybar/config'
alias vimalias='nvim ~/.config/aliasrc'
alias vimpolybar='nvim ~/.config/polybar/config'

alias py3=python3
# low-level stuff and C related
alias objdump='objdump -Mintel'
alias gdb='gdb -q'
alias nasm='nasm -w+all'
alias gcc='gcc -Wall'

# display hexdump in canonical form
alias hd='hexdump -C'

# daily routine
alias lh='ls -lah'
alias ff='find . -name $1'
alias mkcd='_(){ mkdir -p $1; cd $1; }; _'
alias untar='tar -xvf '
alias sshadd='eval `ssh-agent -s`; ssh-add '
# show file permissions as octal number
alias sco='stat -c "%a %n"'
# copy to clickboard from terminal
alias xsel='xsel -b'
alias c='clear'
alias e='exit'
# when I make typos it can be handy | don't judge me)
alias ды='ls'
alias св='cd'

# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# tree aliaces
alias tree='tree --dirsfirst'

# git aliases | TODO keep in git aliases instead
alias gtree='git log --graph --full-history --all --color --pretty=format:"%x1b[33m%h%x09%x09%x1b[32m%d%x1b[0m %x1b[34m%an%x1b[0m   %s" "$@"'

# docker stuff
__dcub() {
    docker-compose build --no-cache $@
}
alias dcub=__dcub
alias dcu='docker-compose up'
#alias dcub='docker-compose up --build'
alias dcubn='docker-compose build --no-cache; docker-compose up'
# Delete all containers
alias drm='docker rm $(docker ps -a -q)'
alias ds='docker container stop $(docker ps -aq)'
# Delete all images
alias drmi='docker rmi $(docker images -q)'
alias dm='docker-machine'
# redis stuff
alias redc='redis-cli'

__export_vars() {
    source "$1"
    export $(cut -d= -f1 "$1")
}

alias source_file=__export_vars

# ssh
__add_ssh_key() {
if [[ -n "$1" ]] && [[ -f ~/.ssh/$1 ]];  then
    eval `ssh-agent -s`>/dev/null 2>&1
    ssh-add ~/.ssh/$1>/dev/null 2>&1
    echo "ssh key $1 was added"
else
    echo "No such key file"
fi
}
alias essh=__add_ssh_key

__add_permanently_ssh_key() {
if [[ -n "$1" ]] && [[ -f ~/.ssh/$1 ]];  then
    res=$(realpath .)
    if [[ -d $res/.git ]]; then
        git config core.sshCommand "ssh -i ~/.ssh/$1"
        echo "Key was added"
    else
        echo "Not in git repository"
    fi
    else
        echo "Not such file"
fi
}
alias pssh=__add_permanently_ssh_key
# network stuff
alias netap='sudo netstat -ap'
alias myip="curl http://ipecho.net/plain; echo"

# keepass
__get_entry_name() {
    if [[ -n "$1" ]]; then
        keepassxc-cli clip ~/Dropbox/KP2A/actual.kdbx $1
    else
        echo "Specify entry name"
    fi
}


alias kcc=__get_entry_name

# changing directories
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'

# django stuff
alias prun="python manage.py runserver 0.0.0.0:8080"
alias psu="python manage.py createsuperuser"
alias pmig="python manage.py migrate"
alias pmake="python manage.py makemigrations"
alias pshell='python manage.py shell -i ipython'
alias ptest='python manage.py test'
alias pipi='pip install -r requirements.txt'
alias svenv='source venv/bin/activate'
alias penv='pipenv'
alias lzd='lazydocker'

alias gcob='git checkout $(git branch | fzf)'

# https://github.com/python-poetry/poetry/issues/536#issuecomment-498308796
#alias poetry="python3 $HOME/.poetry/bin/poetry"

alias speed="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"
alias gstaging='gcloud beta compute ssh --zone "us-central1-a" "dailypass-staging" --project "dailypass"'
alias gprod='gcloud beta compute ssh --zone "asia-southeast1-b" "dailypass-production" --project "dailypass"'
