#!/bin/sh
echo "Some" > ~/test.txt
setxkbmap -option caps:escape
setxkbmap us,ru -option 'grp:alt_shift_toggle'
xinput --set-prop 12 'libinput Accel Speed' 0.5
# Disable middle click
xmodmap -e "pointer = 1 25 3 4 5 6 7 8 9"
